version: 2
updates:
  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: weekly

  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: weekly

  - package-ecosystem: npm
    directory: '/docs'
    schedule:
      interval: weekly

  - package-ecosystem: npm
    directory: '/figma'
    schedule:
      interval: weekly

  - package-ecosystem: npm
    directory: '/packages/panda-preset'
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: '/packages/react'
    schedule:
      interval: daily
